# Python数据分析从入门到放弃（三）
## 数据分析的一 numpy（一）numpy的一般用法

http://blog.sina.com.cn/s/blog_727a8da80102xc3k.html

### 导入 numpy

In [ ]:
import numpy as np

### 读入文本文件

In [3]:
test = np.genfromtxt('test1.txt',delimiter="",dtype=str)
print(test)

["['为你，千千万万遍'," "'献给长成了大人的孩子们'," "'对于“人艰不拆”四个字最彻底的违抗',"
 "'一碗精心熬制的东野牌鸡汤，拒绝很难'," "'活着本身就是人生最大的意义'," "'暗夜独行的残破灵魂，爱与恶本就难分难舍',"
 "'村上之发轫，多少人的青春启蒙'," "'数学好是一种极致的浪漫'," "'你我不过都是虫子'," "'朝向媚俗的一次伟大的进军',"
 "'谁解其中味？'," "'只是青春留下的余烬'," "'一切畅销的因素都有了'," "'在这里看见中国',"
 "'尼采所谓的永劫复归，一场无始无终的梦魇'," "'车手韩寒的公路小说'," "'倒追有风险，入行需谨慎'," "'中国当代城乡生活全景',"
 "'灰姑娘在十九世纪'," "'羽加迪姆勒维奥萨！'," "'封面剧透'," "'无边的黑暗森林，比第一部更为恢弘壮丽',"
 "'革命时期的爱情，随风而逝'," "'犀利又温柔，穿过胸口隐隐作痛'," "'终章，何去何从']"]


### numpy 数组是核心

- 创建一个一维数组
- 创建一个二维数组（矩阵）
- 创建一个三维数组

In [5]:
vector = np.array([5,10,15,20])
matrix = np.array([[5,10,15],[20,25,30],[35,40,45]])
panel = np.array([[[5,10,15],[20,25,30],[35,40,45]],[[55,60,65],[60,75,80],[85,90,95]]])
print('vertor')
print(vector)
print('matrix')
print(matrix)
print('panel')
print(panel)

vertor
[ 5 10 15 20]
matrix
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
panel
[[[ 5 10 15]
  [20 25 30]
  [35 40 45]]

 [[55 60 65]
  [60 75 80]
  [85 90 95]]]


### 常用属性

- shape属性可以看到numpy数组形状
- dtype属性可以看到元素的类型

In [6]:
print('vertor')
print(vector.shape)
print(vector.dtype)
print('matrix')
print(matrix.shape)
print('panel')
print(panel.shape)

vertor
(4,)
int32
matrix
(3, 3)
panel
(2, 3, 3)


# Python 数据分析入门与进阶 
https://www.shiyanlou.com/courses/764

## 多维的创建

NumPy 的核心是多维数组，是通过 ndarray对象做到的，ndarray 对象是一个灵活的数据容器，可以基于此容器对数据进行各种运算。

In [3]:
import numpy as np

print('-----a1-----')
a1 = np.array([1,2,3,4])
print(a1.shape)
print(a1.size)
print(a1.dtype)

print('-----a2-----')
a2 = np.array([[1.0,2.5,3],[0.5,4,9]])
print(a2.shape)
print(a2.size)
print(a2.dtype)
print(a2.min())

print('-----a1,a2-----')
print(a1)
print(a2)
print(type(a1))

-----a1-----
(4,)
4
int64
-----a2-----
(2, 3)
6
float64
0.5
-----a1,a2-----
[1 2 3 4]
[[ 1.   2.5  3. ]
 [ 0.5  4.   9. ]]
<class 'numpy.ndarray'>


a1 为一维数组，a2 为二维数组。二维数组可以想象到类似于 Excel 表中的数据，有行列之分。a2 是一个 2 行，3 列的二维数组。关于这点信息，可以通过 ndarray.shape 得到，比如 a2.shape 输出为 (2, 3), 代表其是一个2行3列的数组。

ndarray.size 属性得到数组的元素个数

ndarray.dtype 属性则记录了数组内部存储的元素是什么类型。

在上面两个例子中，类型分别为 int64 和 float64， dtype 的类型决定了需要存储这些元素的内存大小，是比较底层的信息，

目前只需要知道 NumPy 支持常见的类型，如**浮点数，整数，布尔值，字符串，Python 对象**就行了。

ndarray 还有其他各种方法，比如代码中展示的 min 返回所有元素中的最小元素，