## random

- random.uniform(x, y)方法将随机生成一个实数，它在 [x,y] 范围内。
- random.gauss(mu, sigma) 返回具有高斯分布的随机浮点数。 mu：均值 sigma：标准差

### [np.random.seed()函数](https://zhuanlan.zhihu.com/p/266472620)

- 功能
np.random.seed(n)函数用于生成指定随机数。

- 参数
把seed()中的参数比喻成“堆”；eg. seed(5)：表示第5堆种子。

- 代码实例
seed()中的参数被设置了之后，np.random.seed()可以按顺序产生一组固定的数组，如果使用相同的seed()值，则每次生成的随机数都相同。如果不设置这个值，那么每次生成的随机数不同。但是，只在调用的时候seed()一下并不能使生成的随机数相同，需要每次调用都seed()一下，表示种子相同，从而生成的随机数相同。

In [1]:
# 调用两次seed()，两次产生的随机数相同）
import numpy as np

np.random.seed(1)
L1 = np.random.randn(3,3)
np.random.seed(1)
L2 = np.random.randn(3,3)
print(L1)
print(L2)

[[ 1.62434536 -0.61175641 -0.52817175]
 [-1.07296862  0.86540763 -2.3015387 ]
 [ 1.74481176 -0.7612069   0.3190391 ]]
[[ 1.62434536 -0.61175641 -0.52817175]
 [-1.07296862  0.86540763 -2.3015387 ]
 [ 1.74481176 -0.7612069   0.3190391 ]]


In [2]:
# 只调用一次seed()，两次的产生随机数不同
import numpy as np
np.random.seed(1)

L1 = np.random.randn(3,3)
L2 = np.random.randn(3,3)
print(L1)
print(L2)

[[ 1.62434536 -0.61175641 -0.52817175]
 [-1.07296862  0.86540763 -2.3015387 ]
 [ 1.74481176 -0.7612069   0.3190391 ]]
[[-0.24937038  1.46210794 -2.06014071]
 [-0.3224172  -0.38405435  1.13376944]
 [-1.09989127 -0.17242821 -0.87785842]]


### [random.seed( ) in Python](https://www.geeksforgeeks.org/random-seed-in-python/)

In [1]:
# random module is imported
import random 
for i in range(5):
  
    # Any number can be used in place of '0'.
    random.seed(0)
  
    # Generated random number will be between 1 to 1000.
    print('同 seed')  
    print(random.randint(1, 1000))  

865
865
865
865
865


In [4]:
# random module is imported
import random 
for i in range(5):
  
    # Any number can be used in place of '0'.
    random.seed(0)
    print('同 seed')  
    print('产生1次 random')  
    # Generated random number will be between 1 to 1000.
    print(random.randint(1, 1000))  
    print('产生2次 random')   
    print(random.randint(1, 1000))  

同 seed
产生1次 random
865
产生2次 random
395
同 seed
产生1次 random
865
产生2次 random
395
同 seed
产生1次 random
865
产生2次 random
395
同 seed
产生1次 random
865
产生2次 random
395
同 seed
产生1次 random
865
产生2次 random
395


In [5]:
# importing random module
import random
  
random.seed(3)
print('同 seed')  
# print a random number between 1 and 1000.
print('产生1次 random')  
print(random.randint(1, 1000))
print('产生2次 random')   
print(random.randint(1, 1000))
# if you want to get the same random number again then,
random.seed(3) 
print('同 seed')  
print('产生1次 random')  
print(random.randint(1, 1000))
print('产生2次 random')   
print(random.randint(1, 1000))
# If seed function is not used
  
# Gives totally unpredictable responses.
print('不同 seed')  
print('产生1次 random')  
print(random.randint(1, 1000))
print('产生2次 random')   
print(random.randint(1, 1000))

同 seed
产生1次 random
244
产生2次 random
607
同 seed
产生1次 random
244
产生2次 random
607
不同 seed
产生1次 random
558
产生2次 random
134
